### ISSUE TITLE
A mismatch occurs between handle reference value and running-property

### ISSUE THREAD

**Issue by tetii** [nutti/Index-Visualizer#2]
Index Visualizer ver.1.00.
A mismatch occurs between handle reference value and running-property as follow: 
__handle shows None type but iv_props.running property is True. 

Reproduction:
　Start Index Visualizer, 
　Save a .blend file, 
　Exit Blender application, 
　Open Blender and 
　Load the .blend file.

Result:
![handle_running](https://user-images.githubusercontent.com/37860031/38159319-bde4a78e-34e0-11e8-99f7-a3914cdaad90.png)

Recommendation:
　Monitoring with __handle instead of iv_props.running in IVOperator.invoke and OBJECT_PT_IV.draw.

**Comment by nutti** [comment]
@tetii 

Thanks for bug report again. I will fix this bug too.
But I will wait if you want to fix this bug by yourself.

**Comment by nutti** [comment]
I accepted your PR. thanks for your contribution.
