### ISSUE TITLE
All 3D Views are rendred with primary one's data

### ISSUE THREAD

**Issue by tetii** [nutti/Index-Visualizer#5]
A problem occurs when Blender has multiple 3D Views.Turning on a button doesn't synchronize buttons on other panels. And all 3D views are rendered with parameter of the only one view.

![non-sync](https://user-images.githubusercontent.com/37860031/38301557-dee9a6c0-383a-11e8-8707-a60624d3a3d6.png)

Recommendation:
In IVRenderer.__render_each_data method, area has to be got from context.area.
In IVOperator.invoke method, area has to be got from areas sequence.

**Comment by nutti** [comment]
Your recommendation is correct. Thanks.
I will fix it. (You can also send me pull request too.)
