### ISSUE TITLE
Error occurred in non-mesh type object

### ISSUE THREAD

**Issue by tetii** [nutti/Index-Visualizer#6]
An error occurs in the case active object is non-mesh type object, i.e. editable object such as Armature or Curve.

By the way, I made my second addon, [UV Index Visualizer](https://github.com/tetii/UV-Index-Visualizer), was based on yours. Actually I found these issues #1-4 in mine.
Thank you for your addon.

**Comment by nutti** [comment]
> An error occurs in the case active object is non-mesh type object, i.e. editable object such as Armature or Curve.

Thanks for your report.
maybe, it is caused by missing poll classmethod.

> I made my second addon, UV Index Visualizer, was based on yours. Actually I found these issues #1-4 in mine.

It is a great add-on. I want to use your add-on for my another add-on project.
By the way, it is possible merging your add-on to my add-on if you want.

**Comment by tetii** [comment]
> I want to use your add-on for my another add-on project.
> By the way, it is possible merging your add-on to my add-on if you want.

I accept your proposal with pleasure.

**Comment by nutti** [comment]
great. thanks.
should I merge your add-on? or will you try it with pull request?

**Comment by tetii** [comment]
> should I merge your add-on? or will you try it with pull request?

Thanks
I would like to ask you to do it. 

GitHub is hard for me.

**Comment by nutti** [comment]
> Thanks
> I would like to ask you to do it.
> GitHub is hard for me.

OK, I will merge your add-on.
