### ISSUE TITLE
Blender 2.8 support ?

### ISSUE THREAD

**Issue by ghost** [nutti/Index-Visualizer#9]
Blender 2.8 says "upgrade to 2.8x required" on your add-on
In version 2.79.6 it works fine. Great Add-On!

Will there be a version of your add-on also for Blender 2.8 ?

**Comment by nutti** [comment]
@3DdeepAI 

Thanks for using this add-on.

Is this add-on benefit for Blender 2.8?
You may know Blender includes the visualizing tool for vertices.
So, I think this add-on is no longer needed for us.
But there is requirement to support Blender 2.8 about this add-on, I will tackle.
What do you think?

**Comment by ghost** [comment]
Thank you for your answer. 
I did not find the visualization tool in Blender 2.8
I also searched for "visualization tool for vertices blender 2.8" on the search engine, but I did not find any useful information.

Your tool shows only the selected vertices/faces. That is exactly what I needed. 
Is this option also possible with the in-built visualization tool of Blender 2.8 ?
If not, I would really appreciate support for 2.8 for your add-on
Thank you very much.

**Comment by nutti** [comment]
@3DdeepAI 

I'll show you the procedure to display the vertex/edge/face indices.

At first, you must check the **Developer Extras** at Preferences to show the develpers only menu.

<img width="740" alt="github_pic0" src="https://user-images.githubusercontent.com/1463952/52542454-12569100-2de3-11e9-95eb-792b0c5834f3.png">

Then, check **Indices** on the overlay menu at View3D.
You can see the vertex/edge/face indices.

<img width="578" alt="github_pic1" src="https://user-images.githubusercontent.com/1463952/52542472-3d40e500-2de3-11e9-9322-bcb1e8205a89.png">

Does this fulfill your requirements?

**Comment by ghost** [comment]
Thank you for that info. In my 2.8 version, there is no "Develop" box, but I found it under "Display"
Yes, I think that seems to fullfill my requirements.

**Comment by helpmenowmark** [comment]
I must have looked for 4 hours for this solution.    Thank You!    Now I'd like to change the font to something I can see.

**Comment by LeanderSilur** [comment]
Font Color can be changed under 
_Preferences > Themes > 3D View > Face Angle Text_.

![image](https://user-images.githubusercontent.com/24634045/66268176-07051980-e83b-11e9-8377-c55fb0d2fa94.png)
